Repository yash982000/Competitive-Programming, pull requests merged in 2020-10, with the labels that each got.

#1 Add files via upload
  ACM-ICPC/ICPC ECNA 2005 E - Reliable Nets.cpp
  ACM-ICPC/ICPC ECNA 2016 D - Lost in Translation.cpp
  ACM-ICPC/ICPC ECNA 2016 G - That's One Hanoi-ed Teacher.java
  ACM-ICPC/ICPC NAQ 2016 C - Big Truck.cpp
  ACM-ICPC/ICPC NAQ 2016 D - Brackets.cpp
  ACM-ICPC/ICPC NAQ 2016 G - Inverse Factorial.py
  ACM-ICPC/ICPC NAQ 2016 J - Quick Estimates.cpp
  ACM-ICPC/ICPC PACNW 2016 A - Alphabet.cpp
  ACM-ICPC/ICPC PACNW 2016 C - Cameras.cpp
  ACM-ICPC/ICPC PACNW 2016 J - Shopping.cpp
  ACM-ICPC/Vera and LCS.cpp
  ACM-ICPC/Vera and Outfits.py
Labels: hactoberfest

#5 Some Solutions of codeforces
  Ichihime and Triangle.cpp
  Lift Requests.cpp
  Minimum Product.cpp
  harshilTrippleSort.cpp
  infiniteFence.cpp
  infix to postfix.cpp
  magicjar.cpp
  makeGood1.cpp
  middleofthecontest.cpp
  minimalSquare.cpp
Labels: hactoberfest, hactoberfest-accepted

#8 Codechef Solutions
  ADAMAT.java
  TREE2.java
Labels: hactoberfest, hactoberfest-accepted

#13 Optimized code
  742-A.cpp
Labels: hactoberfest, hactoberfest-accepted

#15 CodeChef Solutions
  CarSell.cpp
  StrangeNo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 Codeforces solutions
  113A.cpp
  260A.cpp
  EC87-B.cpp
  GradeAllocation.cpp
Labels: hacktoberfest, hacktoberfest-accepted
